AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for an ACM Certificate

Resources:

  MyCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: 'cjolivar.serveraccess.link'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: 'cjolivar.serveraccess.link'
          HostedZoneId: Z0206762ADO5JH04R7F7

Outputs:
  CertificateArn:
    Description: 'ARN of the ACM certificate'
    Value: !Ref MyCertificate