AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation Template for an S3 Bucket

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'my-s3-bucket-example'
      AccessControl: Private

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref MyS3Bucket
