AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for an S3 Bucket

Resources:

  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'my-s3-bucket-example-${AWS::AccountId}-${AWS::Region}'
      AccessControl: Private

  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: "S3-TestUser"

  S3UserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Users:
        - !Ref S3User    
      ManagedPolicyName: S3UserPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:put*
              - s3:get*
            Resource: "*"
            
  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AccountId}:user/${IamUserName}'

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref MyS3Bucket
  S3BucketArn:
    Description: 'ARN of the S3 bucket'
    Value: !GetAtt MyS3Bucket.Arn
