AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for an S3 Bucket

Resources:

  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'my-s3-bucket-example-${AWS::Region}-${AWS::AccountId}'
      AccessControl: Private
      WebsiteConfiguration:  
        IndexDocument: index.html
        ErrorDocument: error.html

  S3User:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: "S3-TestUser"

  S3UserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Users:
        - !Ref S3User    
      ManagedPolicyName: S3UserPolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Action:
              - s3:put*
              - s3:get*
              - s3:delete*
            Resource: "*"

  MyCloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties: 
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access Identity for S3 Bucket

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${AWS::AccountId}:user/${S3User}'
                - !GetAtt MyCloudFrontOriginAccessIdentity.IamArn
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'

  MyCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt MyS3Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${MyCloudFrontOriginAccessIdentity}'
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin  
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref MyS3Bucket
  S3BucketArn:
    Description: 'ARN of the S3 bucket'
    Value: !GetAtt MyS3Bucket.Arn
  WebsiteURL:
    Value: !Sub 'http://${MyCloudFrontDistribution.DomainName}'
    Description: URL for the static website
